### ISSUE TITLE
The OpenAL check fails on a recent Ubuntu install even if OpenAL is installed.

### ISSUE THREAD

**Issue by ngld** [scp-fs2open/fsoinstaller#3]
The `libopenal1` package is installed and `/usr/lib/x86_64-linux-gnu/libopenal.so.1` exists but `System.loadLibrary("openal");` fails.
This causes the Installer to incorrectly report that OpenAL isn't installed. I guess it's trying to load `openal.so` or `libopenal.so`. Neither of those exist.

**Comment by Goober5000** [comment]
The Installer tries to load 'OpenAL32' and 'openal' from both the system path and the application path.  Is there another token it should try, e.g. 'libopenal'?

I don't have Linux myself so I'm not able to test.  I know at least one user reported that `System.loadLibrary("openal")` succeeded.

**Comment by ngld** [comment]
Sorry for the late reply. I honestly can't figure out a way to solve this in Java.
The installer should try and load `libopenal.so.1` (the important part is the `.1` at the end). It already tries `libopenal.so` but that file doesn't exist.

I've tried `System.loadLibrary("libopenal.so.1");` and `System.loadLibrary("/usr/lib/libopenal.so.1");`.
The first fails with java claiming it can't find the file and the seocnd fails because directory separators aren't allowed in a library name.

**Comment by Goober5000** [comment]
Specifying the entire path works on Windows, but I guess Linux is different.  Try `System.load("/usr/lib/libopenal.so.1");` instead.  (Note `load` instead of `loadLibrary`.)

**Comment by ngld** [comment]
That's it! `System.load("/usr/lib/x86_64-linux-gnu/libopenal.so.1");` works!
You should also check `System.load("/usr/lib/libopenal.so.1");` because other distributions (i.e. ArchLinux) use that path.

If you don't want to hardcode these paths, an alternative would be to use ldconfig:
```
# ldconfig -p | grep libopenal.so
	libopenal.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libopenal.so.1
```
However, I don't think that's necessary. The full list of possible paths should be:
```
/usr/lib/libopenal.so.1
/usr/lib64/libopenal.so.1
/usr/lib/x86_64-linux-gnu/libopenal.so.1
```

It'd be nice if Java offered a proper API for this. In C a simple `dlopen("libopenal.so.1");` would work.

**Comment by Goober5000** [comment]
Glad to hear it. :)  I will add these to the OpenAL check routine.

**Comment by niffiwan** [comment]
I think using ```ldconfig -p ``` would be a better idea, because every distribution has its own way handling libraries, for instance 32 bit vs 64 bit. For instance of 32bit Ubuntu you probably need this: ```/usr/lib/i386-linux-gnu/libopenal.so.1```

More ideas here for other POSIX OS's
https://stackoverflow.com/questions/2230467/how-to-get-the-system-library-path-on-unix-linux-freebsd

**Comment by ngld** [comment]
You're right, I forgot about 32bit. However, then you also have to deal with the fact that a 64bit Ubuntu system might have a 32bit OpenAL library. The installer won't be able to load that because the Java process would be running in 64bit mode so maybe it won't matter.

Maybe this check should just be removed and be handled by the launcher? After all it depends on whether the user is going to launch a 32bit or 64bit build. Also, there might be other libraries missing (this is mostly solved by the AppImage builds, though).
